# Generated by Django 4.1 on 2023-02-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
